# Generated by Django 2.2 on 2019-04-18 10:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('textArticle', models.TextField()),
                ('datePub', models.DateTimeField(verbose_name=datetime.datetime(2019, 4, 18, 10, 12, 17, 441160, tzinfo=utc))),
                ('likeIt', models.IntegerField(default=0)),
            ],
        ),
    ]
