# Generated by Django 2.2 on 2019-04-18 10:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterField(
            model_name='articles',
            name='datePub',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 4, 18, 10, 20, 33, 487608, tzinfo=utc)),
        ),
    ]
