# Generated by Django 2.2 on 2019-04-18 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190418_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='datePub',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 18, 11, 1, 26, 984410, tzinfo=utc)),
        ),
    ]
