# Generated by Django 2.2 on 2019-04-18 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190418_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='datePub',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
